module.exports = [
  { cnpj: '32319996000199', apelido: 'Kinea Prev Ações', nome: 'KINEA PREV AÇÕES FUNDO DE INVESTIMENTO EM COTAS DE FUNDOS DE INVESTIMENTO' },
  { cnpj: '37555170000142', apelido: 'Hunter Total Return', nome: 'ITAÚ FLEXPREV HUNTER TOTAL RETURN MULTIMERCADO FICFI' },
  { cnpj: '', nome: '' },
  { cnpj: '', nome: '' },
  { cnpj: '', nome: '' },
  { cnpj: '', nome: '' },
  { cnpj: '', nome: '' },
  { cnpj: '', nome: '' },
  { cnpj: '', nome: '' },
  { cnpj: '', nome: '' },
  { cnpj: '', nome: '' },
  { cnpj: '', nome: '' },
  { cnpj: '', nome: '' },
  { cnpj: '', nome: '' },
  { cnpj: '', nome: '' },
  { cnpj: '', nome: '' },
  { cnpj: '', nome: '' },
]